export const POST_DELETE__INIT = "POST_DELETE__INIT";
export const POST_DELETE__REQUEST = "POST_DELETE__REQUEST";
export const POST_DELETE__SUCCESS = "POST_DELETE__SUCCESS";
export const POST_DELETE__FAIL = "POST_DELETE__FAIL";
