export const POSTS_GET_ALL__INIT = "POSTS_GET_ALL__INIT";
export const POSTS_GET_ALL__REQUEST = "POSTS_GET_ALL__REQUEST";
export const POSTS_GET_ALL__SUCCESS = "POSTS_GET_ALL__SUCCESS";
export const POSTS_GET_ALL__FAIL = "POSTS_GET_ALL__FAIL";
